stages:
    - build
    - deploy

build_gateway:
    image: node:20
    stage: build
    tags:
        - remote-dev
    script:
        - echo "Building Gateway"
        - cd apps/gateway
        - yarn install
        - yarn build

build_community_service:
    stage: build
    tags:
        - remote-dev
    script:
        - echo "Building Community Service"
        - cd apps/community-service
        - yarn install
        - yarn build

deploy:
    stage: deploy
    tags:
        - remote
    script:
        - echo "Deploying to Remote Dev Server"
        - docker compose -f docker-compose.yml down
        - docker compose -f docker-compose.yml up -d --build
