stages:
    - build
    - deploy

# variables:
#     NODE_IMAGE: node:20
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""

build_gateway:
    # image: ${NODE_IMAGE}
    stage: build
    tags:
        - remote-shell-dev
    script:
        - echo "Building Gateway"
        - cd apps/gateway
        - yarn install
        - yarn build

build_community_service:
    # image: ${NODE_IMAGE}
    stage: build
    tags:
        - remote-shell-dev
    script:
        - echo "Building Community Service"
        - cd apps/community-service
        - yarn install
        - yarn build

deploy:
    # image: docker:latest
    stage: deploy
    tags:
        - remote-shell-dev
    # before_script:
    #     - apk add --no-cache docker-compose
    script:
        - echo "Deploying to Remote Dev Server"
        - docker compose -f docker-compose.yml down
        - docker compose -f docker-compose.yml up -d --build