stages:
    - build

build_gateway:
    stage: build
    tags:
        - nestjs
    script:
        - export PATH="/opt/homebrew/bin:$PATH"
        - cd apps/gateway 
        - yarn install
        - yarn build
    artifacts:
        paths:
            - apps/gateway/dist/
        expire_in: 3 day