stages:
    - install
    - build

install_dependencies:
    stage: install
    tags:
        - nestjs
    script:
        - export PATH="/opt/homebrew/bin:$PATH"
        - yarn install

build_gateway:
    stage: build
    tags:
        - nestjs
    script:
        - export PATH="/opt/homebrew/bin:$PATH"
        - yarn --cwd apps/gateway build
