before_script:
    - git update-index --assume-unchanged redis/redis.conf

stages:
    - build
    - deploy

variables:
    YARN_CACHE_FOLDER: .yarn-cache
#     NODE_IMAGE: node:20

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
          when: always
          variables:
            GIT_STRATEGY: fetch
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
          when: always
          variables:
            GIT_STRATEGY: fetch
        - when: never
    auto_cancel:
        on_new_commit: interruptible

cache: &global_cache
    key:
        files:
            - yarn.lock
    paths:
        - .yarn-cache
    policy: pull-push

deploy:
    stage: deploy
    tags:
        - remote-shell-dev
    variables:
        GIT_STRATEGY: fetch
        GIT_CLEAN_FLAGS: -ffdx -e redis/redis.conf
    interruptible: true
    script:
        - echo "Cleaning up Docker to free space..."
        - docker system prune -af
        # ❌ DON'T run this: - docker volume prune -f
        - echo "Deploying to Remote Dev Server"
        - docker compose -f docker-compose.yml down
        - docker rm -f $(docker ps -a -q --filter name=rabbitmq) || true
        - docker rmi $(docker images rabbitmq:3-management -q) || true
        - docker compose -f docker-compose.yml pull
        - docker compose -f docker-compose.yml up -d --build
