image: node:18-alpine

stages:
    - install
    - build
    - test

install_dependencies:
    stage: install
    script:
        - npm install -g yarn
        - export PATH="$PATH:/opt/homebrew/bin"
        - yarn install

build_gateway:
    stage: build
    tags: 
        - nestjs
    script:
        - npm install -g yarn  
        - yarn --cwd apps/gateway build