stages:
    - install
    - build

install_dependencies:
    stage: install
    tags:
        - nestjs
    script:
        - export PATH="/opt/homebrew/bin:$PATH"
        - yarn install
        - cd apps/gateway && yarn install
        - cd ../..

build_gateway:
    stage: build
    tags:
        - nestjs
    script:
        - export PATH="/opt/homebrew/bin:$PATH"
        - cd apps/gateway && yarn build
