stages:
    - install
    - build

install_dependencies:
    stage: install
    tags:
        - nestjs
    script:
        - cd apps/gateway
        - yarn install

build_gateway:
    stage: build
    tags:
        - nestjs
    script:
        - cd apps/gateway
        - yarn build
