stages:
    - build
    - deploy

variables:
    YARN_CACHE_FOLDER: .yarn-cache
#     NODE_IMAGE: node:20

cache: &global_cache
    key:
        files:
            - yarn.lock
    paths:
        - .yarn-cache
        - apps/gateway/node_modules
        - apps/community-service/node_modules
    policy: pull-push

build_gateway:
    # image: ${NODE_IMAGE}
    stage: build
    tags:
        - remote-shell-dev
    cache:
        <<: *global_cache
        paths:
            - apps/gateway/node_modules
            - .yarn-cache
    script:
        - echo "Building Gateway"
        - cd apps/gateway
        - yarn install
        - yarn build

build_community_service:
    # image: ${NODE_IMAGE}
    stage: build
    tags:
        - remote-shell-community-service-dev
    cache:
        <<: *global_cache
        paths:
            - apps/community-service/node_modules
            - .yarn-cache
    script:
        - echo "Building Community Service"
        - cd apps/community-service
        - yarn install
        - yarn build

deploy:
    # image: docker:latest
    stage: deploy
    tags:
        - remote-shell-dev
    # before_script:
    #     - apk add --no-cache docker-compose
    script:
        - echo "Deploying to Remote Dev Server"
        - docker compose -f docker-compose.yml down
        - docker compose -f docker-compose.yml up -d --build