services:
    gateway:
        build: 
            context: .
            dockerfile: apps/gateway/Dockerfile
        ports:
            - "8000:8000"
        environment:
            PORT: 8000
            RABBITMQ_URL: amqp://rabbitmq:5672
        depends_on:
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"    
            - "15672:15672"  
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    rabbitmq_data: