// table-names.ts
export const TableNames = {
    IELTS_EXAM: 'ieltsExam',
    CITY: 'city',
    IELTS_REGISTRATION_STUDENT: 'ieltsRegistrationStudent',
    MOCK_REGISTRATION: 'mockRegistration',
    MOCK_REGISTRATION_STUDENT: 'mockRegistrationStudent',
    JOB_HUNTING: 'jobHunting',
    COMPANY: 'company',
    CV: 'cv',
    UNIVERSITY: 'universities',
    FACULTY: 'faculties',
    PROGRAM: 'programs',
    CERTIFICATE_REQUIREMENT: 'certificateRequirements',
    SURVEY: 'survey',
    EVENT: 'event',
    EVENT_REGISTRATION_STUDENT: 'eventRegistrationStudent',
    COURSE: 'course',
    FAQ: 'faq',
    FAQ_CATEGORY: 'faqCategory',
};
