// table-names.ts
export const TableNames = {
    IELTS_EXAM: 'ieltsExam',
    CITY: 'city',
    IELTS_REGISTRATION_STUDENT: 'ieltsRegistrationStudent',
    MOCK_REGISTRATION: 'mockRegistration',
    MOCK_REGISTRATION_STUDENT: 'mockRegistrationStudent',
    JOB_HUNTING: 'jobHunting',
    COMPANY: 'company',
    CV: 'cv',
    UNIVERSITY: 'university',
    FACULTY: 'faculty',
    PROGRAM: 'program',
    CERTIFICATE_REQUIREMENT: 'certificateRequirement',
    SURVEY: 'survey',
    EVENT: 'event',
    EVENT_REGISTRATION_STUDENT: 'eventRegistrationStudent',
    COURSE: 'course',
    FAQ: 'faq',
    FAQ_CATEGORY: 'faqCategory',
    NEWS: 'news',
    NEWS_CATEGORY: 'newsCategory',
    STORY: 'story',
    STORY_ITEM: 'storyItem',
    SHOP_CATEGORY: 'shopCategory',
    SHOP_PRODUCT: 'shopProduct',
    SHOP_ORDER: 'shopOrder',
};
