version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-stories-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/stories
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_QUEUE=microservice_queue
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nest_network
    restart: unless-stopped
    
  mongodb:
    image: mongo:latest
    container_name: nest-stories-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nest_network
    restart: unless-stopped
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: nest-stories-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nest_network
    restart: unless-stopped

networks:
  nest_network:
    driver: bridge

volumes:
  mongodb_data:
  rabbitmq_data:
