FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY apps/gateway/package.json apps/gateway/yarn.lock ./

RUN yarn global add @nestjs/cli
RUN yarn install --frozen-lockfile
RUN yarn install

COPY . .

RUN yarn --cwd apps/gateway build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/apps/gateway/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 8000
CMD ["node", "dist/main.js"]
